version: '3'

services:
  redis:
    image: redis:latest
    expose:
      - '3000'
    ports:
      - "6379:6379"

  express-typescript-docker:
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    container_name: express-typescript-docker
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
